name: game_parking
version: 2.0.2

description: Game Parking is a Rush Hour game. EDNetCore is a domain model framework.
homepage: http://ondart.me/
documentation: http://goo.gl/LDhRwm
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  ednet_core:
    path: ../../../ednet_cms/packages/ednet_core